### ISSUE TITLE
Using one of your EventPlugin only inside a specific component.

### ISSUE THREAD

**Issue by bertrandg** [kryops/ng2-events#4]
Hi,
Your library is really usefull and interesting to understand how works angular, thanks for it!

I got a question not directly related to `ng2-events` but you seems to deeply understand how angular manage template event listeners "under the hood" so, maybe, you can help me (if that's not right place for, just close the issue..).

I got an angular library named [angular-split](https://github.com/bertrandg/angular-split) and would like to use your [UndetectedEventPlugin](https://github.com/kryops/ng2-events/blob/master/src/undetected/undetected.event.ts) only inside my library component template.

I've tried to add the EventPlugin inside component `providers` but it's not recognized (no error but handler functions never called):
```` js
@Component({
    selector: 'as-split',
    providers: [{
            provide: EVENT_MANAGER_PLUGINS,
            useClass: UndetectedEventPlugin,
            multi: true
    }],
    template: `<div (undetected.click)="x()"></div>`,
})
export class SplitComponent {...}
````

On the contrary, if I add it inside library module `providers`, it works too well because all app using my library module have access to `(undetected.anyevent)` syntax which I don't want:
```` js
@NgModule({
    imports: [...], declarations: [...], exports: [...],
    providers: [
        {
            provide: EVENT_MANAGER_PLUGINS,
            useClass: UndetectedEventPlugin,
            multi: true
        }
    ]
})
export class AngularSplitModule {}
````

Any clue about it with your knowledge?

**Comment by kryops** [comment]
Hi @bertrandg 

Sadly, I don't know that much about Angular's internals, I just read about the `EVENT_MANAGER_PLUGINS` somewhere and wanted to have some fun with it.

You'll probably have a better chance for a good answer on StackOverflow or [Gitter](https://gitter.im/angular/angular)

My guess would be that rendering happens on a module level and ignores the component's providers. Following `EVENT_MANAGER_PLUGINS` backwards in the Angular source leads you to something like this:

```
Compiler > NgModuleFactory > NgModuleRef > ComponentResolverFactory > ComponentResolver > RendererFactory2 > Renderer2 > EventManager > EVENT_MANAGER_PLUGINS
```

As for a workaround to your problem, did you try to add some sort of [Feature Module](https://angular.io/guide/feature-modules) that provided the event for just your component?

**Comment by bertrandg** [comment]
Hi,
Thanks to answer.

No sadly, adding a new module doesn't solve this, all my tests indicates whatever the module it is inside, it's global to the app and usable everywhere.
And if I add it inside a lazy loaded module, it's available nowhere even inside this module..

Only way I see to limit scope is to use a directive like this:
https://github.com/bertrandg/angular-split/blob/7b6b26a329dc39eebb6d591ce1512dbbda47516e/projects/angular-split/src/lib/directive/eventOutsideZone.directive.ts

I will still try on Gitter! :)

**Comment by bertrandg** [comment]
Check this for people interested about:
https://stackoverflow.com/questions/53835649/angular-how-to-use-a-custom-eventplugin-only-inside-specific-component-instead

That's not possible.
